#!/usr/bin/env python3
"""Standalone Colab split cell: Label Studio export folder -> ds/ + data.yaml.

Same behavior as prepare_dataset.py but ZIP-FREE, for running directly in a
Colab cell after you've already unzipped the "YOLO with images" export. It
recursively globs images and labels under the export folder (so it doesn't
matter whether they sit at the root or one level down), does a seeded 70/20/10
split, writes the Ultralytics ds/ layout, and generates data.yaml. Single
class -> 0: crack.

Colab usage:
    !unzip -q export.zip -d export
    !python split_colab.py export --out ds --seed 42
"""
import argparse
import random
import shutil
from pathlib import Path

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
SPLITS = {"train": 0.70, "val": 0.20, "test": 0.10}


def pair_files(root: Path):
    """Recursively match every image under root to its <stem>.txt label."""
    # Index all label files by stem so images/ and labels/ can live anywhere.
    labels = {p.stem: p for p in root.rglob("*.txt") if p.name != "classes.txt"}
    pairs = []
    for img in sorted(root.rglob("*")):
        if img.suffix.lower() in IMG_EXTS and img.is_file():
            pairs.append((img, labels.get(img.stem)))
    return pairs


def split_pairs(pairs, seed: int):
    """Deterministically split pairs into train/val/test buckets."""
    rng = random.Random(seed)
    shuffled = pairs[:]
    rng.shuffle(shuffled)
    n = len(shuffled)
    n_train = int(n * SPLITS["train"])
    n_val = int(n * SPLITS["val"])
    return {
        "train": shuffled[:n_train],
        "val": shuffled[n_train:n_train + n_val],
        "test": shuffled[n_train + n_val:],
    }


def write_split(out: Path, split: str, pairs):
    """Copy images/labels into out/<split>/images and out/<split>/labels."""
    img_dir = out / split / "images"
    lbl_dir = out / split / "labels"
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)
    for img, label in pairs:
        shutil.copy2(img, img_dir / img.name)
        if label is not None:
            shutil.copy2(label, lbl_dir / label.name)


def write_yaml(out: Path):
    """Write the Ultralytics data.yaml describing the single 'crack' class."""
    yaml = (
        f"# Auto-generated by split_colab.py\n"
        f"path: {out.resolve().as_posix()}\n"
        f"train: train/images\n"
        f"val: val/images\n"
        f"test: test/images\n\n"
        f"nc: 1\n"
        f"names:\n  0: crack\n"
    )
    (out / "data.yaml").write_text(yaml, encoding="utf-8")


def print_summary(splits):
    """Print a small table of image / labelled counts per split."""
    print(f"\n{'Split':<8}{'Images':>8}{'Labelled':>10}")
    print("-" * 26)
    total = labelled = 0
    for name in ("train", "val", "test"):
        pairs = splits[name]
        n_lab = sum(1 for _, lab in pairs if lab is not None)
        total += len(pairs)
        labelled += n_lab
        print(f"{name:<8}{len(pairs):>8}{n_lab:>10}")
    print("-" * 26)
    print(f"{'total':<8}{total:>8}{labelled:>10}\n")


def main():
    ap = argparse.ArgumentParser(description="Zip-free Colab split for Label Studio YOLO export.")
    ap.add_argument("export_dir", type=Path, help="Unzipped export folder (contains images + labels)")
    ap.add_argument("--out", type=Path, default=Path("ds"), help="Output dataset dir")
    ap.add_argument("--seed", type=int, default=42, help="Split RNG seed")
    args = ap.parse_args()

    if not args.export_dir.is_dir():
        raise SystemExit(f"Not a directory: {args.export_dir}")
    if args.out.exists():
        shutil.rmtree(args.out)

    pairs = pair_files(args.export_dir)
    if not pairs:
        raise SystemExit("No images found under export dir.")

    splits = split_pairs(pairs, args.seed)
    for name, bucket in splits.items():
        write_split(args.out, name, bucket)
    write_yaml(args.out)

    print_summary(splits)
    print(f"data.yaml -> {(args.out / 'data.yaml').resolve()}")


if __name__ == "__main__":
    main()
